### ISSUE TITLE
[Question] How do I build this?

### ISSUE THREAD

**Issue by temuri416** [joehoyle/php-v8js#2]
Does this produce an .so extension?

Thanks!

**Comment by roborourke** [comment]
@temuri416 it does, there are `.so` extensions available on the repo releases page so you don't need to build it yourself if you don't want to.

If you want to build from scratch you'll to install Rust and then `cargo build` eg.

```
curl https://sh.rustup.rs -sSf | sh -s
source $HOME/.cargo/env
cargo build
```

Should give you a `libv8js.so` in the `target/debug/` directory.

**Comment by joehoyle** [comment]
@temuri416 in most cases it's recommended to use a pre-built version at https://github.com/joehoyle/php-v8js/releases/tag/0.0.2 (let me know if we don't have a build suiting you). You _can_ build it ofcourse, but it means setting up the whole rust + php toolchain
