### ISSUE TITLE
Add builds for debian bullseye and ARM architecture

### ISSUE THREAD

**Issue by roborourke** [joehoyle/php-v8js#3]
For Altis's PHP container we need builds for Debian Bullseye as well both AMD and ARM architectures.

**Comment by joehoyle** [comment]
@roborourke [x86_64-unknown-linux-gnu-libv8js.so](https://github.com/joehoyle/php-v8js/releases/download/0.0.2/x86_64-unknown-linux-gnu-libv8js.so) should work for the AMD build-- or did you into into issues with that?

**Comment by roborourke** [comment]
Yeah I did try it but it failed to load - specifically I think it said it was built against a different version of core PHP or something like that, I guess because it's Ubuntu latest. I can't remember exactly what the error message was now but you could swap out the built binary in the container for the one you linked to see it.

**Comment by joehoyle** [comment]
ahh, ok, I think that might actually be due to it being build under php 8.1, I'm changing that now.

**Comment by joehoyle** [comment]
Ok I've added support for ARM and PHP 8.0/PHP 8.1, you can see the new artifacts in https://github.com/joehoyle/php-v8js/releases/tag/0.0.3
